In [1]:
import numpy as np

In [2]:
l = [1,2,3,4]

In [4]:
ar = np.array(l)

In [5]:
ar

array([1, 2, 3, 4])

In [6]:
type(ar)

numpy.ndarray

In [8]:
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

In [9]:
np.asarray(l)

array([1, 2, 3, 4])

In [10]:
a = [2,3,4]

In [11]:
np.asanyarray(a)

array([2, 3, 4])

In [12]:
b = np.matrix(l)

In [13]:
b

matrix([[1, 2, 3, 4]])

In [14]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [15]:
a = np.array(l)

In [16]:
a

array([1, 2, 3, 4])

In [17]:
c = a

In [18]:
c

array([1, 2, 3, 4])

In [19]:
c[0]

1

In [20]:
c[0] = 100

In [21]:
c

array([100,   2,   3,   4])

In [22]:
a

array([100,   2,   3,   4])

In [23]:
d = np.copy(a)

In [24]:
d

array([100,   2,   3,   4])

In [25]:
a

array([100,   2,   3,   4])

In [26]:
a[1] = 400

In [27]:
a

array([100, 400,   3,   4])

In [28]:
d

array([100,   2,   3,   4])

In [29]:
np.fromfunction(lambda i, j : i == j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [30]:
np.fromfunction(lambda i, j : i * j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [32]:
iterable = (i*i for i in range(5))

In [34]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [35]:
np.fromstring('234 234', sep = ' ')

array([234., 234.])

In [37]:
np.fromstring('4, 5', sep = ',')

array([4., 5.])

In [38]:
#Numpy - Data Types

In [39]:
l = [2,3,4,5,6]

In [40]:
ar = np.array(l)

In [41]:
ar

array([2, 3, 4, 5, 6])

In [42]:
ar.ndim

1

In [43]:
ar2 = np.array([[1,2,3,4], [2,3,4,5]])

In [44]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [45]:
ar2.ndim

2

In [46]:
ar2.size

8

In [47]:
ar

array([2, 3, 4, 5, 6])

In [48]:
ar.size

5

In [49]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [50]:
ar.shape

(5,)

In [51]:
ar2.shape

(2, 4)

In [52]:
ar.dtype

dtype('int64')

In [53]:
ar2.dtype

dtype('int64')

In [54]:
ar22 = np.array([(1.4,45,45), (23,45,66)])

In [55]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [56]:
ar22.dtype

dtype('float64')

In [57]:
list(range(5))

[0, 1, 2, 3, 4]

In [58]:
list(range(0.1, 5))

TypeError: 'float' object cannot be interpreted as an integer

In [59]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [61]:
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [62]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [63]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [64]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [65]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [68]:
ar4 = np.zeros((3,4,2,3))

In [69]:
ar4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [70]:
np.ones(4)

array([1., 1., 1., 1.])

In [71]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [74]:
on = np.ones((2,3,2))

In [75]:
on + 5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [76]:
on * 5

array([[[5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.]]])

In [78]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [79]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [2]:
import numpy as np


In [3]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [4]:
np.logspace(2,5 , 10, base = 2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [7]:
arr = np.random.randn(3,4)

In [8]:
import pandas as pd

In [9]:
pd.DataFrame(arr)

0         1         2         3
0 -1.242413 -0.276606  0.363853 -0.365129
1 -0.021921 -0.295224 -1.310376 -0.111666
2 -0.563563  1.736686 -0.463572 -0.066914

In [14]:
np.random.rand(3,4)

array([[0.07542779, 0.06753515, 0.29702677, 0.95206055],
       [0.73371575, 0.37710287, 0.17687971, 0.47137094],
       [0.57689684, 0.51066311, 0.81742814, 0.43818901]])

In [15]:
np.random.randint(1,118,(3,4))

array([[10, 66, 46,  2],
       [34, 12, 46, 86],
       [98, 90, 37, 69]])

In [16]:
np.random.randint(1,110,(300,400))   

array([[ 51,  75,  66, ...,  45,  37,  96],
       [ 70,  72,  50, ...,  17,  39,  73],
       [ 57,  52, 101, ...,  23,  98,  39],
       ...,
       [ 22,  55,  87, ...,  95,  11,  79],
       [ 64,  14,  74, ...,  32,   5,  32],
       [ 87,  93,  30, ...,  27, 104,  21]])

In [17]:
pd.DataFrame(np.random.randint(1,110,(300,400)) )

0    1    2    3    4    5    6    7    8    9    ...  390  391  392  \
0     73   17   40   33   46  106    7   76   79   55  ...   61   56  105   
1     12   12   57    9   13   73   56  109   31    9  ...   46   80    2   
2      3   64   69   15   46   14   84   93   36    4  ...   79   99    7   
3     26   53   80   78   20   94   48   81   14   72  ...   58    9   56   
4      4    2  102   56   36   34   47  102   27  102  ...   18   70   42   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
295   18   24   33   94  106    7   64   57   72   40  ...    6   52   79   
296   80   17  103   77   12   53   26   98   35   90  ...   29   90   30   
297   58   34  100   49   51   56   18   82  106   42  ...  106   87   91   
298  106   65   28   83   45   23   67   12   30   13  ...   58   20   88   
299   79   41   28   19   31   53   76   16   27   89  ...   74   89   18   

     393  394  395  396  397  398  399  
0     38   14    8   84   29   49   71  
1     63   36   32    6   16   33   25  
2     99   45   63   89   69  104   98  
3    104   16   52  104   52   67   74  
4     84   43   64   97    1   89   51  
..   ...  ...  ...  ...  ...  ...  ...  
295   21    3  107   57   67   92   51  
296   49  100   88   44   78   53   47  
297    7    3   14   91   43  105   20  
298   35   52   83   27    7   73   59  
299   30   24   14   68   84   45   68  

[300 rows x 400 columns]

In [18]:
pd.DataFrame(np.random.randint(1,110,(300,400))).to_csv('test.csv')

In [19]:
arr = np.random.rand(3,4)

In [20]:
arr

array([[0.05270085, 0.44336162, 0.84371261, 0.90055334],
       [0.31056696, 0.22586779, 0.53870835, 0.44107081],
       [0.99025328, 0.63591742, 0.1988079 , 0.48480783]])

In [22]:
arr1 = arr.reshape(6,2)

In [23]:
arr1

array([[0.05270085, 0.44336162],
       [0.84371261, 0.90055334],
       [0.31056696, 0.22586779],
       [0.53870835, 0.44107081],
       [0.99025328, 0.63591742],
       [0.1988079 , 0.48480783]])

In [26]:
arr1[1][1]

0.9005533421397743

In [30]:
arr1[2:5, 1]

array([0.22586779, 0.44107081, 0.63591742])

In [31]:
arr = np.random.randint(1,100, (5,5))

In [32]:
arr

array([[51, 19, 76, 91, 86],
       [46, 42,  6,  3, 36],
       [30, 93, 48, 36, 38],
       [92, 74,  9, 43, 66],
       [77, 34, 39, 80, 78]])

In [34]:
arr[arr > 50]

array([51, 76, 91, 86, 93, 92, 74, 66, 77, 80, 78])

In [35]:
arr[2:4, [1,2]]

array([[93, 48],
       [74,  9]])

In [36]:
arr[0][0] = 500

In [37]:
arr

array([[500,  19,  76,  91,  86],
       [ 46,  42,   6,   3,  36],
       [ 30,  93,  48,  36,  38],
       [ 92,  74,   9,  43,  66],
       [ 77,  34,  39,  80,  78]])

In [40]:
arr1 = np.random.randint(1,3, (3,3))
arr2 = np.random.randint(1,3, (3,3))

In [41]:
arr1

array([[2, 2, 1],
       [1, 1, 2],
       [2, 2, 1]])

In [42]:
arr2

array([[2, 2, 1],
       [2, 1, 2],
       [1, 2, 1]])

In [44]:
arr1+arr2

array([[4, 4, 2],
       [3, 2, 4],
       [3, 4, 2]])

In [45]:
arr1-arr2

array([[ 0,  0,  0],
       [-1,  0,  0],
       [ 1,  0,  0]])

In [46]:
arr1/arr2

array([[1. , 1. , 1. ],
       [0.5, 1. , 1. ],
       [2. , 1. , 1. ]])

In [47]:
arr1*arr2

array([[4, 4, 1],
       [2, 1, 4],
       [2, 4, 1]])

In [48]:
arr1@arr2

array([[9, 8, 7],
       [6, 7, 5],
       [9, 8, 7]])

In [49]:
arr1/0

/tmp/ipykernel_1446/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [50]:
arr1+100

array([[102, 102, 101],
       [101, 101, 102],
       [102, 102, 101]])

In [51]:
arr1**2

array([[4, 4, 1],
       [1, 1, 4],
       [4, 4, 1]])

In [52]:
#Numpy - Broadcasting

In [53]:
arr = np.zeros((4,4))

In [54]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [55]:
row = np.array([1,2,3,4])

In [56]:
row

array([1, 2, 3, 4])

In [57]:
arr + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [58]:
row.shape

(4,)

In [59]:
row.T

array([1, 2, 3, 4])

In [60]:
col = np.array([[1,2,3,4]])

In [64]:
col.T + arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [66]:
col

array([[1, 2, 3, 4]])

In [67]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.random.randint