In [ ]:
#NUmpy - Array Manipulation

In [ ]:
import numpy as np

In [4]:
arr = np.random.randint(1,10, (3,4))

In [5]:
arr

array([[1, 1, 9, 1],
       [6, 1, 7, 5],
       [6, 9, 1, 3]])

In [6]:
arr.reshape(6,2)

array([[1, 1],
       [9, 1],
       [6, 1],
       [7, 5],
       [6, 9],
       [1, 3]])

In [7]:
arr.reshape(2,6)

array([[1, 1, 9, 1, 6, 1],
       [7, 5, 6, 9, 1, 3]])

In [8]:
arr.reshape(2,7)

ValueError: cannot reshape array of size 12 into shape (2,7)

In [9]:
arr.reshape(2, -25647)

array([[1, 1, 9, 1, 6, 1],
       [7, 5, 6, 9, 1, 3]])

In [10]:
arr.T

array([[1, 6, 6],
       [1, 1, 9],
       [9, 7, 1],
       [1, 5, 3]])

In [11]:
arr.flatten()

array([1, 1, 9, 1, 6, 1, 7, 5, 6, 9, 1, 3])

In [12]:
arr1 = np.array([1,2,3,3,4])

In [13]:
arr1.ndim

1

In [14]:
np.expand_dims(arr1, axis = 1)

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [15]:
np.expand_dims(arr1, axis = 0)

array([[1, 2, 3, 3, 4]])

In [16]:
arr

array([[1, 1, 9, 1],
       [6, 1, 7, 5],
       [6, 9, 1, 3]])

In [17]:
np.squeeze(arr)

array([[1, 1, 9, 1],
       [6, 1, 7, 5],
       [6, 9, 1, 3]])

In [18]:
data = np.array([[1], [2], [3]])

In [19]:
data

array([[1],
       [2],
       [3]])

In [20]:
np.squeeze(data)

array([1, 2, 3])

In [21]:
arr1

array([1, 2, 3, 3, 4])

In [22]:
np.repeat(arr1, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [23]:
np.roll(arr1, 2)

array([3, 4, 1, 2, 3])

In [24]:
arr1

array([1, 2, 3, 3, 4])

In [25]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [26]:
#Numpy - Binary Operation

In [27]:
arr1 = np.random.randint(1,10, (3,4))

In [28]:
arr2 = np.random.randint(1,10, (3,4))

In [29]:
arr1

array([[3, 4, 9, 7],
       [6, 7, 2, 5],
       [3, 3, 9, 6]])

In [30]:
arr2

array([[4, 1, 7, 6],
       [8, 1, 8, 7],
       [6, 5, 7, 3]])

In [31]:
arr1+arr2

array([[ 7,  5, 16, 13],
       [14,  8, 10, 12],
       [ 9,  8, 16,  9]])

In [32]:
arr1*arr2

array([[12,  4, 63, 42],
       [48,  7, 16, 35],
       [18, 15, 63, 18]])

In [33]:
arr1/arr2

array([[0.75      , 4.        , 1.28571429, 1.16666667],
       [0.75      , 7.        , 0.25      , 0.71428571],
       [0.5       , 0.6       , 1.28571429, 2.        ]])

In [34]:
arr1-arr2

array([[-1,  3,  2,  1],
       [-2,  6, -6, -2],
       [-3, -2,  2,  3]])

In [35]:
arr1%arr2

array([[3, 0, 2, 1],
       [6, 0, 2, 5],
       [3, 3, 2, 0]])

In [36]:
arr1**arr2

array([[     81,       4, 4782969,  117649],
       [1679616,       7,     256,   78125],
       [    729,     243, 4782969,     216]])

In [37]:
arr1 & arr2

array([[0, 0, 1, 6],
       [0, 1, 0, 5],
       [2, 1, 1, 2]])

In [38]:
arr1

array([[3, 4, 9, 7],
       [6, 7, 2, 5],
       [3, 3, 9, 6]])

In [39]:
arr2

array([[4, 1, 7, 6],
       [8, 1, 8, 7],
       [6, 5, 7, 3]])

In [40]:
~arr1

array([[ -4,  -5, -10,  -8],
       [ -7,  -8,  -3,  -6],
       [ -4,  -4, -10,  -7]])

In [41]:
arr|arr2

array([[ 5,  1, 15,  7],
       [14,  1, 15,  7],
       [ 6, 13,  7,  3]])

In [42]:
arr1>arr2

array([[False,  True,  True,  True],
       [False,  True, False, False],
       [False, False,  True,  True]])

In [43]:
#NUmpy - String Function

In [45]:
arr = np.array(['nilesh', 'Kumar'])

In [46]:
arr

array(['nilesh', 'Kumar'], dtype='<U6')

In [47]:
np.char.upper(arr)

array(['NILESH', 'KUMAR'], dtype='<U6')

In [48]:
np.char.title(arr)

array(['Nilesh', 'Kumar'], dtype='<U6')

In [50]:
np.char.capitalize(arr)

array(['Nilesh', 'Kumar'], dtype='<U6')

In [51]:
#NUmpy - Mathematical Function

In [52]:
arr1

array([[3, 4, 9, 7],
       [6, 7, 2, 5],
       [3, 3, 9, 6]])

In [53]:
np.sin(arr1)

array([[ 0.14112001, -0.7568025 ,  0.41211849,  0.6569866 ],
       [-0.2794155 ,  0.6569866 ,  0.90929743, -0.95892427],
       [ 0.14112001,  0.14112001,  0.41211849, -0.2794155 ]])

In [54]:
np.cos(arr1)

array([[-0.9899925 , -0.65364362, -0.91113026,  0.75390225],
       [ 0.96017029,  0.75390225, -0.41614684,  0.28366219],
       [-0.9899925 , -0.9899925 , -0.91113026,  0.96017029]])

In [55]:
np.tan(arr1)

array([[-0.14254654,  1.15782128, -0.45231566,  0.87144798],
       [-0.29100619,  0.87144798, -2.18503986, -3.38051501],
       [-0.14254654, -0.14254654, -0.45231566, -0.29100619]])

In [56]:
np.tanh(arr1)

array([[0.99505475, 0.9993293 , 0.99999997, 0.99999834],
       [0.99998771, 0.99999834, 0.96402758, 0.9999092 ],
       [0.99505475, 0.99505475, 0.99999997, 0.99998771]])

In [57]:
np.log10(arr1)

array([[0.47712125, 0.60205999, 0.95424251, 0.84509804],
       [0.77815125, 0.84509804, 0.30103   , 0.69897   ],
       [0.47712125, 0.47712125, 0.95424251, 0.77815125]])

In [58]:
np.exp(arr1)

array([[2.00855369e+01, 5.45981500e+01, 8.10308393e+03, 1.09663316e+03],
       [4.03428793e+02, 1.09663316e+03, 7.38905610e+00, 1.48413159e+02],
       [2.00855369e+01, 2.00855369e+01, 8.10308393e+03, 4.03428793e+02]])

In [59]:
np.sqrt(arr1)

array([[1.73205081, 2.        , 3.        , 2.64575131],
       [2.44948974, 2.64575131, 1.41421356, 2.23606798],
       [1.73205081, 1.73205081, 3.        , 2.44948974]])

In [61]:
np.power(arr1, 2)

array([[ 9, 16, 81, 49],
       [36, 49,  4, 25],
       [ 9,  9, 81, 36]])

In [62]:
np.mean(arr1)

5.333333333333333

In [67]:
import numpy as np


In [69]:
np.median(arr1)

5.5

In [ ]:
np.