In [1]:
#Sort, Search & Counting Function

In [2]:
import numpy as np

In [4]:
arr = np.array([4,3,5,5,6,63,4,6,7,9,63])

In [5]:
arr

array([ 4,  3,  5,  5,  6, 63,  4,  6,  7,  9, 63])

In [6]:
np.sort(arr)

array([ 3,  4,  4,  5,  5,  6,  6,  7,  9, 63, 63])

In [7]:
np.searchsorted(arr, 34)

5

In [8]:
arr1 = np.array([0,345,453,0,0,0,0,0])

In [9]:
np.count_nonzero(arr1)

2

In [10]:
arr

array([ 4,  3,  5,  5,  6, 63,  4,  6,  7,  9, 63])

In [11]:
np.where(arr > 6)

(array([ 5,  8,  9, 10]),)

In [12]:
np.extract(arr>3, arr)

array([ 4,  5,  5,  6, 63,  4,  6,  7,  9, 63])

In [13]:
#NUmpy - Byte Swapping

In [14]:
arr.byteswap()

array([ 288230376151711744,  216172782113783808,  360287970189639680,
        360287970189639680,  432345564227567616, 4539628424389459968,
        288230376151711744,  432345564227567616,  504403158265495552,
        648518346341351424, 4539628424389459968])

In [15]:
#Numpy - Cpoies & View

In [16]:
arr

array([ 4,  3,  5,  5,  6, 63,  4,  6,  7,  9, 63])

In [17]:
a = np.copy(arr)

In [18]:
b = arr.view()

In [24]:
b = arr

In [19]:
b

array([ 4,  3,  5,  5,  6, 63,  4,  6,  7,  9, 63])

In [20]:
arr

array([ 4,  3,  5,  5,  6, 63,  4,  6,  7,  9, 63])

In [21]:
b[0] = 67

In [22]:
b

array([67,  3,  5,  5,  6, 63,  4,  6,  7,  9, 63])

In [23]:
arr

array([67,  3,  5,  5,  6, 63,  4,  6,  7,  9, 63])

In [25]:
#Numpy -- Matrix Library

In [26]:
import numpy.matlib as nm

In [27]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [28]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [29]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])